import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Card from "../components/card";
import styles from "../styles/Home.module.css";
import coffeeStoresData from "../data/coffee-stores.json";

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log("works");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View Stores Nearby"
          handleOnBannerBtnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Coffee Stores</h2>
            <div className="styles.cardLayout">
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl || ""}
                    href={`/coffee-store/${coffeeStore.id}`}
                    className={styles.card}
                    key={coffeeStore.id}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps(context) {


  const url = 'https://api.foursquare.com/v3/places/search?ll=43.65267326999575,-79.39545615725015&query=stores&limit=6&v=20220105&limit=6"';
  const options = {
    method: 'GET',
    headers: {
      Accept: 'application/json',
      Authorization: process.env.NEXT_PUBLIC_FOURSQUARE_API_KEY
    }
  };

  const request = await fetch(url, options);
  const data = await request.json();
  console.log(data.results)


  return {
    props: {
      coffeeStores:   data.results
      
    }, // will be passed to the page component as props
  };
}
